---
# Helm version number
helm_version: "v3.10.0"
# "kubectl" version number
kubectl_version: "1.25.0"


architecture: "amd64" # other possible values: "386","arm64","arm","ppc64le","s390x"
# Operating system on which "kubectl" should run on
kubectl_os: "linux"  # use "darwin" for MacOS X, "windows" for Windows


# Owner of binaries
owner: "root"
# Group of binaries
group: "root"


download_dir: "{{ x_ansible_download_dir | default(ansible_env.HOME + '/.ansible/tmp/downloads') }}"
# Specifies the permissions of the binaries
binary_mode: "0755"


# Mirror to download Helm from
helm_mirror: 'https://get.helm.sh'
# Dir where Helm should be installed
helm_install_dir: '/usr/local/share/helm'
helm_bin_path: '/usr/local/bin/helm'
#===============================================================================================================Kubectl block===================================

kubectl_download_filetype: "binary"
# SHA512 checksum of the .tar.gz file (see https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.25.md#client-binaries)
kubectl_checksum_archive: "sha512:34a7e9a496fff31a3afa6f5f7245212d051de3c2966e42a662040bde8a733c1cf55ce2e50227813fd29c6db758687a453a7df66b6c32f7f2c93959280c4e130a"
# SHA512 checksum of the binary (see https://storage.googleapis.com/kubernetes-release/release/v1.25.0/bin/linux/amd64/kubectl.sha512)
kubectl_checksum_binary: "sha512:fac91d79079672954b9ae9f80b9845fbf373e1c4d3663a84cc1538f89bf70cb85faee1bcd01b6263449f4a2995e7117e1c85ed8e5f137732650e8635b4ecee09"
# Where to install "kubectl" binary
kubectl_bin_directory: "/usr/local/bin"
