---
# tasks file for bashrc
- name: make sure function is in bashrc
  blockinfile:
    dest: ~/.bashrc
    src: "files/.bashrc.j2"


- name: run the function from shell after sourcing .bashrc
  shell: source ~/.bashrc && my_test_func
  register: func_result

- name: check result
  debug:
    var: func_result.stdout
