---
- name: JenkinsPort
  hosts: vpn
  become: true

  pre_tasks:
    - include_tasks: debian-setup.yml
      when: ansible_os_family == 'Debian'

  vars:
    jenkins_hostname: "{{ public_ip_addr }}"
    jenkins_http_port: 8080

  roles:
    - java
    - jenkins

  post_tasks:
    - name: Ensure Jenkins is running on the specified port.
      uri:
        url: "http://{{ public_ip_addr }}:{{ jenkins_http_port }}"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
