---
- name: install Helm
  become: yes
  unarchive:
    src: '{{ download_dir }}/{{ helm_redis_filename }}'
    remote_src: yes
    dest: '{{ helm_install_dir }}'
    extra_opts:
      - '--strip-components=1'
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: 'o-w'
    creates: '{{ helm_install_dir }}/helm'

- name: create helm link
  become: yes
  file:
    src: '{{ helm_install_dir }}/helm'
    dest: '{{ helm_bin_path }}'
    state: link
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "{{ binary_mode }}"
