---
- include_tasks: helm_prepare.yml
  tags: helm_prepare

- include_tasks: helm_install.yml
  tags: helm_install

- include_tasks: "setup-{{ kubectl_download_filetype|lower }}.yml"
  tags: kubectl_install
