---
- name: Download kubectl binary
  ansible.builtin.get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubectl_version }}/bin/{{ kubectl_os }}/{{ architecture }}/kubectl"
    checksum: "{{ kubectl_checksum_binary }}"
    dest: "{{ download_dir }}"
    mode: 0600
  tags:
    - kubectl

- name: Copy kubectl binary to destination directory
  become: yes
  ansible.builtin.copy:
    src: "{{ download_dir }}/{{ item }}"
    dest: "{{ kubectl_bin_directory }}/{{ item }}"
    mode: "{{ binary_mode }}"
    owner: "{{ owner }}"
    group: "{{ group }}"
    remote_src: true
  with_items:
    - kubectl
