---
- name: Check Ansible version
  command: ansible --version
  register: ansibleVersion


- name: Print os version
  debug:
    msg: "OS Family: {{ ansible_os_family }}"


- name: Update aptitude debian based
  apt:
    upgrade: full
    update_cache: yes
    autoclean: yes
    autoremove: yes
  when:
    - ansible_os_family == "Debian"


- name: Update aptitude centos based
  yum:
    upgrade: full
    update_cache: yes
    autoclean: yes
    autoremove: yes
  when:
    - ansible_os_family == "RedHat"


- name: include needed variables
  include_vars: "{{ ansible_os_family }}.yml"


- name: Install Apache
  apt:
    name: "{{ apache_name }}"
    update_cache: yes
    state: latest
