---
- hosts: "{{ hostname }}"
  become: yes

  tasks:
    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - build-essential
          - python3-pip
        state: present
        update-cache: yes


    - name: Install docker gpg key
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        state: present

    - name: Add docker repo
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    - name: Install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Add gitlab-runner user to docker group
      user:
        name: gitlab-runner
        append: yes
        groups: docker


    - name: Install gitlab runner
      shell: |
        curl -LJO https://gitlab-runner-downloads.s3.amazonaws.com/latest/deb/gitlab-runner_amd64.deb; \
        dpkg -i gitlab-runner_amd64.deb
      args:
        creates: /usr/bin/gitlab-runner